---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-mi
  namespace: app1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-fuse