---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "client_id"
    azure.workload.identity/tenant-id : "CLIENT_ID_TO_REPLACE"
  labels:
    azure.workload.identity/use: "true"
  name: "sa1"
  namespace: app1