---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-fuse
provisioner: blob.csi.azure.com
parameters:
  protocol: fuse2
  resourceGroup: STORAGE_RESOURCE_GROUP_TO_REPLACE
  storageAccount: STORAGE_ACCOUNT_TO_REPLACE
  containerName: CONTAINER_NAME_TO_REPLACE
  AzureStorageAuthType: MSI
  AzureStorageIdentityClientID: CLIENT_ID_TO_REPLACE
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
